// <auto-generated />
namespace Vente_Aux_Enchere_Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class c9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(c9));
        
        string IMigrationMetadata.Id
        {
            get { return "202004250029030_c9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
